### ISSUE TITLE
why not toString() ?

### ISSUE THREAD

**Issue by stevenvachon** [jonschlinkert/is-plain-object#1]
```js
return obj.toString() === "[object Object]";
```

`constructor` is not reliable across different "realms" (windows/iframes/frames).

**Comment by stevenvachon** [comment]
```js
return obj.toString === "[object Object]";
```

`constructor` is not reliable across different "realms" (windows/iframes/frames).

**Comment by jonschlinkert** [comment]
hmm, good point. same for `instanceof`. I think we would need to do something more like:

```js
return obj && obj.toString() === "[object Object]";
```
otherwise `null` will be true.

**Comment by jonschlinkert** [comment]
actually, what about `Object.create(null)` and `new Whatever`. Those will probably be `true` with this, which would be a breaking change, and technically not a "plain" object.

**Comment by stevenvachon** [comment]
Hmm
```js
console.log( Object.create(null) ); //=> {}
```
but
```js
function Whatever(){}
console.log( new Whatever().toString() ); //=> "[object Object]"
```

**Comment by jonschlinkert** [comment]
But also `Object.create(null).toString()` won't work. Since `null` is the prototype, there won't be a `.toString()` method, so this will throw an error.

**Comment by stevenvachon** [comment]
could do
```js
return Object.prototype.toString.call( Object.create(null) ) === "[object Object]";
```
but it still doesn't work here:
```js
function Whatever(){}
console.log( Object.prototype.toString.call( new Whatever ) ); //=> "[object Object]"
```

**Comment by stevenvachon** [comment]
```js
function Whatever(){}
console.log( new Whatever().hasOwnProperty("isPropertyOf") ); //=> false
```

**Comment by stevenvachon** [comment]
how's this?:
```js
function isPlainObject(obj) {
    if ( Object.prototype.toString.call( Object.create(null) ) === "[object Object]" ) {
        return obj.hasOwnProperty("isPropertyOf");
    }
    return false;
}
``

**Comment by jonschlinkert** [comment]
I was just thinking something similar. one sec

**Comment by jonschlinkert** [comment]
I'm thinking something more like this:

```js
function isPlainObject(o) {
  if (!isObject(o) || o && typeof o.toString === 'undefined') {
    return false;
  }

  if (o.nodeType || o === o.window) {
    return false;
  }

  var ctor = o && o.constructor;
  if (!hasOwn.call(o, 'constructor') && (typeof ctor === 'function' && !(ctor instanceof ctor))) {
    return false;
  }

  if(ctor && !({}).hasOwnProperty.call(ctor.prototype, 'isPrototypeOf')) {
    return false;
  }

  return true;
}
```
This passes everything, and since this issue would really only be relevant in the browser (frames), the additional `.nodeType` and `.window` checks are probably good anyway. 

thoughts?

**Comment by stevenvachon** [comment]
```js
function isPlainObject(o) {
  // truthy is slower than strict equals
  // removed unnecessary `o &&` because what follows wouldn't run if the former failed
  if (isObject(o) === false || typeof o.toString === 'undefined') {
    return false;
  }

  // strict equals
  if (o.nodeType !== undefined || o === o.window) {
    return false;
  }

  // `o &&` removed because we already know that it's truthy
  var ctor = o.constructor;
  // hasOwn --> Object.prototype.hasOwnProperty
  // two strict equals
  // not sure what `ctor instanceof ctor` is for ?
  if (Object.prototype.hasOwnProperty.call(o, 'constructor') === false && typeof ctor === 'function' && ctor instanceof ctor === false) {
    return false;
  }

  // `ctor &&` removed because we already know that it's truth
  // what does `!({})` accomplish? why not use Object.prototype.hasOwnProperty ?
  if(!({}).hasOwnProperty.call(ctor.prototype, 'isPrototypeOf')) {
    return false;
  }

  return true;
}
```

**Comment by stevenvachon** [comment]
I'm thinking that the `if (o.nodeType != undefined` part might cause issues with virtual DOMs

**Comment by stevenvachon** [comment]
Then again, would a virtual dom object be a plain object?

**Comment by jonschlinkert** [comment]
> removed unnecessary `o`

just noticed that too. thanks I didn't "clean up" yet.

> why not use Object.prototype.hasOwnProperty ?

I was initially going to change all of them to `({})` but started using `hasOwn` and missed that one. fixed

> truthy is slower than strict equals

The `isobject` lib handles this already. 

> I'm thinking that the if (o.nodeType != undefined part might cause issues with virtual DOM

how so? It's not strictly necessary since it's just an opportunity to exit early. we can remove if you think it might cause issues.

how about if we simplify to:

```js
function isPlainObject(o) {
  if (!isObject(o) || typeof o.toString === 'undefined') {
    return false;
  }

  if (o.nodeType || o === o.window) {
    return false;
  }

  var ctor = o && o.constructor;
  if(ctor && !hasOwn.call(ctor.prototype, 'isPrototypeOf')) {
    return false;
  }

  return true;
}
```

**Comment by jonschlinkert** [comment]
oh, just noticed you did a strict comparison on `nodeType`, I don't think that's necessary

**Comment by jonschlinkert** [comment]
> Then again, would a virtual dom object be a plain object?

no, since it's not created by the object constructor. 

(fwiw, Lo-dash also considers an object that is created with a prototype of `null` to be a plain object. if we wanted to follow that convention we could remove `typeof o.toString === 'undefined'`)

**Comment by stevenvachon** [comment]
>> truthy is slower than strict equals

> The isobject lib handles this already.

But you're still checking the result with a truthy. Truthy is `==`, and the first value checked in such a comparison is not Boolean: https://twitter.com/stevenvachon/status/541027060236701696

Same goes for `if (o.nodeType` and all other truthies.

Virtual dom objects probably aren't plain objects and if they are, that issue might be for another day. Most anyone wouldn't virtual dom objects in such a way that'd require `isPlainObject` anyway.

Interesting on the null prototype. However:
```js
console.log( {}.prototype ); //=> undefined
```

**Comment by stevenvachon** [comment]
Actually, yeah, the first check of a truthy/`==` is `===`, so `!isObject(o)` is efficient. The others aren't, though.

**Comment by jonschlinkert** [comment]
yeah, was just going to say that I also forgot (when I said that) that based on this conversation I had changed `isobject` locally to be:

```js
function isObject(o) {
  return Object.prototype.toString.call(o) === '[object Object]'
    && typeof o === 'object';
}
```

**Comment by jonschlinkert** [comment]
do you want to do a pr?

**Comment by stevenvachon** [comment]
> do you want to do a pr?

Nah, it's ok. Most interested in getting an awesome non-jquery `isPlainObject` out there :)

By `hasOwn`, do you mean?: https://www.npmjs.com/package/hasown

**Comment by stevenvachon** [comment]
By the way, it seems like truthy/falsy does `undefined` and `null` before it does `Boolean`. So, strict equals would be faster.

**Comment by stevenvachon** [comment]
```js
function isPlainObject(o) {
  if (isObject(o) === false || o.nodeType !== undefined || o === o.window) {
    return false;
  }

  var ctor = o.constructor;
  return isObject(o) === true && Object.hasOwnProperty.call(ctor.prototype, 'isPrototypeOf') === false;
}
```

**Comment by stevenvachon** [comment]
hmm, removed `ctor`, because it'd be one less variable to garbage collect.

**Comment by stevenvachon** [comment]
meh, yeah, I guess I'll do a pr as I can work with the tests

**Comment by jonschlinkert** [comment]
> Nah, it's ok. Most interested in getting an awesome non-jquery isPlainObject out there :)

:+1: 

> By hasOwn, do you mean?

wow, I'm off tonight... sorry, here are the variables at the top of the script:

```js
var isObject = require('isobject');
var hasOwn = Object.prototype.hasOwnProperty;
```

> So, strict equals would be faster.

but we're technically not creating a new comparison, and a _logical not_ does a strict comparison, correct?

> hmm, removed ctor, because it'd be one less variable to garbage collect.

perhaps, but what's more expensive, the lookup or the reference? I'm fine with not using the variable, but it's probably extremely negligible here, considering we would only hit this point after other values have been disqualified

**Comment by jonschlinkert** [comment]
> guess I'll do a pr as I can work with the tests

sounds good, thanks!

**Comment by stevenvachon** [comment]
Logical nots attempt to convert the value to a boolean (using some internal `ToBoolean`) which runs the algorithm listed at the link above.

Yeah, garbage collection vs lookup. The lookup might be faster because the call object has already been made when the var was passed to the function.

**Comment by jonschlinkert** [comment]
> Logical nots attempt to convert the value to a boolean (using some internal ToBoolean) which runs the algorithm listed at the link above.

Great knowledge to have, thank you for sharing that!

> The lookup might be faster because the call object has already been made when the var was passed to the function.

so maybe keep the variable and use strict equals on `isObject()`?

**Comment by jonschlinkert** [comment]
> so maybe keep the variable and use strict equals on isObject()?

ah, nvm I had your point about the lookup the other way around.

**Comment by stevenvachon** [comment]
Why would you change isObject to
```js
function isObject(o) {
  return Object.prototype.toString.call(o) === '[object Object]'
    && typeof o === 'object';
}
```
? that makes `assert(isObject(/foo/) === true)` fail.

**Comment by jonschlinkert** [comment]
seems like just doing `typeof val` would be enough to get that answer, but I was debating on that. so I didn't actually commit any changes or push it up. 

I know regex is an object, but I'm also thinking that that's probably not the use case for a lib like `isObject`. what are your thoughts on why `isObject(/foo/)` should be true?

**Comment by stevenvachon** [comment]
This one may make the most sense: https://github.com/ljharb/is-object/blob/master/index.js because Array *is* an Object and `typeof null === "object"`. I would expect any object to be `isObject(obj)===true`.

**Comment by stevenvachon** [comment]
But at the same time, `isObject(array)===true` is a common annoyance. I'm not sure which is best, but since the other already exists, might as well keep yours the way it is. Perhaps point to his lib instead of yours since we don't need to slow the script down with `Array.isArray`

**Comment by stevenvachon** [comment]
Because if `isObject(new Foo)===true`, then `isObject(/foo/)===true` would be consistent.

**Comment by stevenvachon** [comment]
What do you think of this?:
```js
function isObject(obj) {
  return obj !== null
    && typeof obj === 'object';
}

function isObjectObject(obj) {
  return isObject(obj) === true
    && Object.prototype.toString.call(obj) === '[object Object]';
}

module.exports = function isPlainObject(o) {
  // Checking nodeType might be too restricting on a plain Object's keys
  // What is `o.window` ?
  if (isObjectObject(o) === false || o.nodeType !== undefined || o === o.window) {
    return false;
  }
  
  // If has modified constructor or prototype
  if (typeof o.constructor !== 'function' || isObjectObject(o.constructor.prototype) === false) {
    return false;
  }
  
  // If constructor does not have an Object-specific method
  if (o.constructor.prototype.hasOwnProperty('isPrototypeOf') === false) {
    return false;
  }
  
  // Most likely a plain Object
  return true;
};
```

**Comment by jonschlinkert** [comment]
> What do you think of this?:

Do all of the unit tests pass? with the exception of maybe `Object.create(null)`, I don't see a compelling reason to change any other results. also would prefer to keep `isObject` as a dep. 

> What is `o.window` ?

https://developer.mozilla.org/en-US/docs/Web/API/Window/window. Again, just adding this since it was a case that came to mind for browser use. I'm fine with getting rid of `nodeType` and `window`, as they will probably be eliminated by the `constructor` checks anyway. although I'm not 100% sure though and I haven't tested those.

fwiw, I do a lot of benchmarks, and although I personally disagree with the common notion that "micro-optimizations" are useless, because some of them turn out to be surprisingly **not** micro, and small optimizations in micro-libs have a compounding throughout the dependency tree. But if I'm to be honest, here I think if we want to keep moving code around for the sake of making it more performant, it might be worth considering adding some benchmarks so we can see the actual impact of these decisions. 

My gut is that the simple act of making sure the statements are in the correct order to decrease the odds that a second comparison will be done will probably have the biggest impact (the code looks like it does this already, but it completely depends on the use case. this is where the benchmarks fail)

**Comment by stevenvachon** [comment]
All unit tests pass. We should add a phantomjs test, though.

`Array.isArray` is likely the slowest function in there and this script doesn't need it when we have `Object.prototype.toString`.

I agree about micro-optimizations. They're worth considering, especially in small libraries like this that can quite literally be used in everything everywhere. Benchmarks are a good idea and won't necessarily fail if we run many different ones for comparison.

**Comment by jonschlinkert** [comment]
all sounds good to me. I can add the benchmarks, but it might be a couple of days, I'm up against a deadline. would you want to do the phantomjs tests? 

thank you for the dialogue!

**Comment by jonschlinkert** [comment]
made you a collab in case you need this to happen faster than i can get around to it. I'll add you to npm as well

**Comment by jonschlinkert** [comment]
k, added to npm

**Comment by stevenvachon** [comment]
Cool, thanks!

**Comment by stevenvachon** [comment]
I updated my above code, what do you think?

**Comment by stevenvachon** [comment]
`Array.isArray` is actually much faster than `Object.prototype.toString.call`: http://jsperf.com/object-tostring-vs-array-isarray
