### ISSUE TITLE
3.0.0 and Typescript

### ISSUE THREAD

**Issue by damlys** [jonschlinkert/is-plain-object#20]
Hi :wave: I'm not sure if you have used this library with TypeScript project, but this is how I have to import your function:

```
// @ts-ignore
import * as isPlainObject from 'is-plain-object/index.cjs.js';
```

You should add that to readme, because I spend almost 30 minutes to investigate what is going on :dizzy_face:

**Comment by TrySound** [comment]
You need to add `esModuleInterop: true` to your config and import as default. `import * as` cannot be function. TypeScript is wrong here due legacy reasons.

**Comment by damlys** [comment]
I didn't know that option, thank you. I'm closing this issue :ok_hand:
