### ISSUE TITLE
Update readme and package.json

### ISSUE THREAD

**Issue by stevenvachon** [jonschlinkert/is-plain-object#4]
Which version? I don't think it necessarily justifies a v2.0, but it *is* a rewrite.

**Comment by jonschlinkert** [comment]
I think v2.0 is the safe way to go, I'd prefer to err on the safe side with changes to utilities like this.

**Comment by jonschlinkert** [comment]
and thank you!!!

**Comment by jonschlinkert** [comment]
Done. I bumped to 2.0 in package.json and added you to npm as a maintainer, so I'll leave the honors to you to publish. thanks again!

**Comment by stevenvachon** [comment]
Published. Thank you as well!

**Comment by jonschlinkert** [comment]
perfect! thanks
