### ISSUE TITLE
Check property descriptors (getters/setters) ?

### ISSUE THREAD

**Issue by stevenvachon** [jonschlinkert/is-plain-object#9]

**Comment by jonschlinkert** [comment]
Can you give more detail? sorry, I'm not sure what you mean.

**Comment by stevenvachon** [comment]
No problem.
```js
const isPlainObject = require('is-plain-object');
const obj = {};

Object.defineProperty(obj, 'prop', {
  enumerable: false,
  get: function() { return true }
});

isPlainObject(obj);  //-> true
```

I'm wondering if the above should be considered "plain".

**Comment by jonschlinkert** [comment]
That's correct since `obj` was created by the `Object` constructor. 

```js
var obj = {};
// is sugar for
var obj = new Object();
```

**Comment by jonschlinkert** [comment]
Oh, I think I might get where you're coming from. By "plain object" it means that an object was created by the `Object` constructor, versus a class, like `new Foo()`. Not that it doesn't have any additional custom properties, etc.

**Comment by stevenvachon** [comment]
> By "plain object" it means that an object was created by the `Object` constructor, versus a class, like `new Foo()`

Yes. We currently have prototype checks in place to catch this, but we don't catch property descriptors defined with `Object.defineProperty`.

**Comment by jonschlinkert** [comment]
Sorry, I'm struggling to understand what you mean, since `Object.defineProperty` can be used to define a property on any kind of object, and whether or not that property is `enumerable` wouldn't affect how the object was created. The "receiver" of the property is the thing we're checking for, isn't it?

**Comment by stevenvachon** [comment]
You're confusing me :)

I'm talking about `obj` on my code example. If it receives a property descriptor (getter/setter functions), should it still be considered a "plain" object?

**Comment by jonschlinkert** [comment]
Yes. Maybe this will explain better:

```js
const isPlainObject = require('is-plain-object');
const obj = {};
// at this point, we already know that obj is a "plain" object
// since it was created by the `Object` constructor. There is
// nothing we can do to it to make it _not_ plain, regardless of
// the properties (accessors, descriptors, or any other properties)

Object.defineProperty(obj, 'prop', {
  enumerable: false,
  get: function() { return true }
});

isPlainObject(obj);  //-> true

function Foo() {
}

const foo = new Foo();
// at this point, we know that foo is a **not** a "plain" object
// since it was not created by the `Object` constructor. The
// only way we can make it a plain object at this point is
// by doing this: "Foo.prototype.constructor = Object;"

Object.defineProperty(foo, 'prop', {
  enumerable: false,
  get: function() { return true }
});

console.log(isPlainObject(foo));  //-> false

Foo.prototype.constructor = Object;
console.log(isPlainObject(foo));  //-> true
```

**Comment by stevenvachon** [comment]
Ok, so a getter/setters on an otherwise plain object is still plain. Thank you.

**Comment by jonschlinkert** [comment]
sorry for the confusion, thanks for the issue!
